openapi: 3.0.0
info:
  title: 購物車相關 API
  version: 1.0.0

paths:
  /cart:
    get:
      summary: 取得購物車
      tags: [Cart]
      responses:
        '200':
          description: 成功取得購物車
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    
    put:
      summary: 更新整個購物車（會員同步用）
      tags: [Cart]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/CartItem'
      responses:
        '200':
          description: 更新成功

  /cart/items:
    post:
      summary: 加入商品至購物車
      tags: [Cart]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [productId, quantity]
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
                  minimum: 1
      responses:
        '200':
          description: 加入成功
        '400':
          description: 庫存不足或參數錯誤

  /cart/items/{itemId}:
    patch:
      summary: 更新購物車項目數量
      tags: [Cart]
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  minimum: 0
      responses:
        '200':
          description: 更新成功
    
    delete:
      summary: 移除購物車項目
      tags: [Cart]
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 移除成功

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        subtotal:
          type: number
        shipping:
          type: number
        discount:
          type: number
        total:
          type: number
        updatedAt:
          type: string
          format: date-time
    
    CartItem:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        product:
          type: object
        quantity:
          type: integer
        price:
          type: number
        subtotal:
          type: number
        addedAt:
          type: string
          format: date-time
