openapi: 3.0.0
info:
  title: 訂單相關 API
  version: 1.0.0

paths:
  /orders:
    get:
      summary: 取得訂單列表
      tags: [Orders]
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, processing, shipped, delivering, delivered, completed, cancelled]
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  meta:
                    type: object
    
    post:
      summary: 建立訂單
      tags: [Orders]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [items, paymentMethod, shippingInfo]
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
                paymentMethod:
                  type: string
                  enum: [credit-card, atm, cod]
                shippingInfo:
                  $ref: '#/components/schemas/ShippingInfo'
                note:
                  type: string
      responses:
        '201':
          description: 訂單建立成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: 庫存不足或參數錯誤

  /orders/{id}:
    get:
      summary: 取得訂單詳情
      tags: [Orders]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: 訂單不存在

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        status:
          type: string
        paymentMethod:
          type: string
        paymentStatus:
          type: string
        subtotal:
          type: number
        shipping:
          type: number
        discount:
          type: number
        total:
          type: number
        shippingInfo:
          $ref: '#/components/schemas/ShippingInfo'
        trackingNumber:
          type: string
        note:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    
    OrderItem:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        productName:
          type: string
        productImage:
          type: string
        price:
          type: number
        quantity:
          type: integer
        subtotal:
          type: number
    
    ShippingInfo:
      type: object
      required: [recipientName, phone, city, district, address, postalCode]
      properties:
        recipientName:
          type: string
        phone:
          type: string
        city:
          type: string
        district:
          type: string
        address:
          type: string
        postalCode:
          type: string
