openapi: 3.0.0
info:
  title: 產品相關 API
  version: 1.0.0
  description: 電商購物網站產品查詢與分類相關 API

servers:
  - url: http://localhost:3000/api
    description: 開發環境 Mock API

paths:
  /products:
    get:
      summary: 取得產品列表
      description: 支援分類篩選、搜尋、排序與分頁
      tags:
        - Products
      parameters:
        - name: categoryId
          in: query
          schema:
            type: string
          description: 產品類別 ID
        - name: search
          in: query
          schema:
            type: string
          description: 搜尋關鍵字
        - name: minPrice
          in: query
          schema:
            type: number
          description: 最低價格
        - name: maxPrice
          in: query
          schema:
            type: number
          description: 最高價格
        - name: sort
          in: query
          schema:
            type: string
            enum: [price-asc, price-desc, newest, popular]
            default: popular
          description: 排序方式
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: 頁碼
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
          description: 每頁筆數
      responses:
        '200':
          description: 成功取得產品列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 150
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 20
                      hasMore:
                        type: boolean
                        example: true

  /products/{id}:
    get:
      summary: 取得單一產品詳情
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: 產品 ID
      responses:
        '200':
          description: 成功取得產品詳情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: 產品不存在

  /categories:
    get:
      summary: 取得所有產品類別
      description: 回傳階層式類別結構
      tags:
        - Categories
      responses:
        '200':
          description: 成功取得類別列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /categories/{id}:
    get:
      summary: 取得單一類別詳情
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功取得類別詳情

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - slug
        - price
        - images
        - categoryId
        - stock
      properties:
        id:
          type: string
          example: prod-001
        name:
          type: string
          example: 無線藍牙耳機
        slug:
          type: string
          example: wireless-earbuds
        description:
          type: string
        shortDescription:
          type: string
        price:
          type: number
          example: 2990
        originalPrice:
          type: number
        images:
          type: array
          items:
            type: object
        categoryId:
          type: string
        stock:
          type: number
        isFeatured:
          type: boolean
        specs:
          type: array
          items:
            type: object
        tags:
          type: array
          items:
            type: string
        rating:
          type: number
        reviewCount:
          type: integer

    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        parentId:
          type: string
          nullable: true
        children:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        productCount:
          type: integer
